baseURL: "https://hugo-profile.netlify.app"
languageCode: "en-us"
title: "新媒体艺术家 In_K毕振宇 "
theme: "hugo-profile"

outputs:
  home:
    - "HTML"
    - "RSS"
    - "JSON"
  page:
    - "HTML"
    - "RSS"

enableRobotsTXT: true





#services:
  #googleAnalytics:
    #id: G-MEASUREMENT_ID
  #disqus:
    #shortname: your-disqus-shortname

pagination:
  pagerSize: 10


markup:
  goldmark:
    renderer:
      unsafe: true
      hardWraps: true

Menus:
  main:
    - identifier: blog
      name: Artworks
      title: 创作
      url: /artworks
      weight: 1
    - identifier: blog
      name: Projects
      title: 项目
      url: /projects
      weight: 2
    - identifier: blog
      name: About
      title: 介绍
      url: /about
      weight: 3
    #Dropdown menu
    # - identifier: dropdown
    #   title: Example dropdown menu
    #   name: Dropdown
    #   weight: 3
    # - identifier: dropdown1
    #   title: example dropdown 1
    #   name: example 1
    #   url: /#
    #   parent: dropdown
    #   weight: 1
    # - identifier: dropdown2
    #   title: example dropdown 2
    #   name: example 2
    #   url: /#
    #   parent: dropdown
    #   weight: 2

params:
  title: "In_K 毕振宇"
  description: 新媒体艺术家
  # staticPath: ""  # The path to serve the static files from
  favicon: "http://img.inkx.cc/logo.png"

  # Whether to serve bootstrap css and js files from CDN or not. Can be set to true, "css" or "js" to choose between
  # serving both, only the css, or only the js files through the CDN. Any other value will make so that CDN is not used.
  # Note the lack of "" in true, it should be of boolean type.
  useBootstrapCDN: false

  # If you want to load dynamically responsive images from Cloudinary
  # This requires your images to be uploaded + hosted on Cloudinary
  # Uncomment and change YOUR_CLOUD_NAME to the Cloud Name in your Cloudinary console
  # cloudinary_cloud_name: "YOUR_CLOUD_NAME"

  # Whether to add mathjax support on all pages. Alternatively, you can opt-in per page by adding `mathjax: true` in the frontmatter.
  mathjax: false

  # Whether the fade animations on the home page will be enabled
  animate: true

  theme:
    # disableThemeToggle: true
    defaultTheme: "dark" # light

  font:
    fontSize: 1rem # default: 1rem
    fontWeight: 400 # default: 400
    lineHeight: 1.5 # default: 1.5
    textAlign: left # default: left

  # 颜色偏好
  # 在使用颜色的十六进制代码时，必须同时使用引号和 # sign
  color:
  textColor: "#343a40"
  secondaryTextColor: "#6c757d"
  textLinkColor: "#007bff"
  backgroundColor: "#eaedf0"
  secondaryBackgroundColor: "#64ffda1a"
  primaryColor: "#007bff"
  secondaryColor: "#f8f9fa"

  darkmode:
  textColor: "#e4e6eb"
  secondaryTextColor: "#b0b3b8"
  textLinkColor: "#ffffff"
  backgroundColor: "#000000"
  secondaryBackgroundColor: "#212529"
  primaryColor: "#ffffff"
  secondaryColor: "#212529"

  # 自定义菜单menu
  navbar:
    align: ms-auto # Left: ms-auto | center: mx-auto | right: me-auto | Default: ms-auto
    # brandLogo: "/logo.png" # Logo for the brand | default is the favicon variable
    # showBrandLogo: false # Show brand logo in nav bar | default is true
    brandName: "In_K 毕振宇" # Brand name for the brand | default is the title variable
    disableSearch: true
    # searchPlaceholder: "Search"
    stickyNavBar:
      enable : true
      showOnScrollUp : true
    enableSeparator: true
    menus:
      disableAbout: true
      disableExperience: true
      disableEducation: true
      disableProjects: true
      disableCrossover: true
      disableAchievements: true
      disableContact: true

 

  # About
  about:
    enable: true
    title: " "
    image: "http://img.inkx.cc/ink-pfp.jpg"
    content: |-
      新媒体艺术家毕振宇以「In_K」为代号，专注于算法编程驱动的生成式影像创作。他的作品以计算机生成内容为核心，融合艺术与算法、形式与过程，在不断演化的代码逻辑中构建动态的视觉结构。他的实践涵盖从动态影像、互动装置到实时视觉系统，始终保持对系统性与诗意的探索。

      [点击查看详细介绍](https://www.inkx.cc/about/)

      |--------------------
    skills:
      enable: true
      title: "创作版图涵盖:"
      items:
        - "交互编程"
        - "影像装置"
        - "AudioVisual视觉演出"
        - "沉浸式交互影像"
        - "科技艺术"
        - "生成式影像"
        - "AIGC"
        - "媒介理论"
        - "欧陆哲学"
        - "身体技术"
        - "Web3"
        - "艺术评论"

  # projects
  projects:
    enable: true
    title: "Projects"
    items:

      - title: Artworks
        content: 艺术相关的创作，作品。
        image: "http://img.inkx.cc/artwork.jpg"
        featured:
          name: More..
          link: https://www.inkx.cc
        badges:
          - "生成艺术"
          - "媒介理论"

      - title: DROWYEK
        content: DROWYEK是一个AudioVisual项目由冯昊和In_K组成。
        image: "http://img.inkx.cc/drowyek.jpg"
        featured:
          name: More..
          link: https://www.inkx.cc/drowyek
        badges:
          - "AudioVisual视觉演出"
          - "新媒体艺术"
          - "影像装置"

      - title: Projects
        content: 影像装置
        image: "http://img.inkx.cc/projects.jpg"
        featured:
          name: More..
          link: https://www.inkx.cc/projects
        badges:
          - "影像装置"
          - "商业项目"
          - "科技艺术"

      - title: 视觉现场
        content: 演出相关的视觉及现场
        image: "http://img.inkx.cc/visualshow.JPG"
        featured:
          name: More..
          link: https://www.inkx.cc/visualshow
        badges:
          - "沉浸式影像"
          - "VJ舞台视觉"
          - "交互式影像"
     


      - title: 观点Blog
        content: 博客、文章、创作灵感、意图
        image: "http://img.inkx.cc/blog.jpg"
        featured:
          name: More..
          link: https://www.inkx.cc
        badges:
          - "启发"
          - "分享"
          - "灵感"

      - title: 采访讲座分享
        content: 参加过的一些讲座、采访、分享等等。
        image: "http://img.inkx.cc/interview.jpg"
        featured:
          name: More..
          link: https://www.inkx.cc
        badges:
          - "观点"
          - "看法"
          - "态度"


# Experience
  experience:
    enable: false
    title: "激进思想技术"
    items:
      - job: "理想主义者的web3"
        company: "web3/元宇宙"
        featuredLink:
          enable: true
          name: "去观看"
          url: "https://www.inkx.cc"
        content: "I am currently working as a software developer at [example org.](https://example.com) in San Francisco, CA. I am currently working on a project that will be used to help people find the best way to get around the city."

      - job: "艺术家的人工智能"
        company: "AIGC"
        #companyUrl: "https://www.inkx.cc"
        featuredLink:
          enable: true
          url: "https://www.inkx.cc"
        info:
          enable: false
          content:  
        content: |
          I am currently working as a software developer at [example org.](https://example.com) in San Francisco, CA. I am currently working on a project that will be used to help people find the best way to get around the city.

          - Lead backend developer for a product.
          - Created a frontend design for a product.

      - job: "欧陆哲学词典"
        company: "欧陆哲学"
        featuredLink:
          enable: true
          url: "https://example.com"
        content: |
          I am currently working as a software developer at [example org.](https://example.com) in San Francisco, CA. I am currently working on a project that will be used to help people find the best way to get around the city.

          - Lead backend developer for a product.
          - Created a frontend design for a product.




  #Contact
  contact:
    enable: true
    # title: "Custom Name"
    content: work@inkx.cc ｜ WeChat：inkoml

    # formspree:
    #   enable: true # `contact.email` value will be ignored
    #   formId: abcdefgh # Take it from your form's endpoint, like 'https://formspree.io/f/abcdefgh'
    #   emailCaption: "Enter your email address"
    #   messageCaption: "Enter your message here"
    #   messageRows: 5

  footer:
    recentPosts:
      path: "blogs"
      count: 3
      title: Recent Posts
      enable: true
      disableFeaturedImage: false
    socialNetworks:
      bilibili: https://github.com
      instagram: https://instagram.com


  # List pages like blogs and posts
  listPages:
    disableFeaturedImage: false

  # Single pages like blog and post
  singlePages:
    socialShare: true
    readTime:
      enable: false
      content: "min read"
    scrollprogress:
      enable: true
    tags:
      openInNewTab: true

  # For translations
  terms:
    read: "Read"
    toc: "Table Of Contents"
    copyright: "All rights reserved"
    pageNotFound: "Page not found"
    emailText: "Check out this site"

  datesFormat:
    article: "Jun 2, 2025"
    articleList: "Jun 2, 2025"
    articleRecent: "Jun 2, 2025"

  #customScripts: -| # You can add custom scripts which will be added before </body> tag
  #  <script type="text/javascript"><!-- any script here --></script>
